// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSMgvztIvHjQ_3vF8xnjxAZMtftdW_alc',
    appId: '1:360358999157:web:fcd070892d5df8650c743c',
    messagingSenderId: '360358999157',
    projectId: 'chat-app-38a80',
    authDomain: 'chat-app-38a80.firebaseapp.com',
    storageBucket: 'chat-app-38a80.firebasestorage.app',
    measurementId: 'G-74QQ7V3K37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJlsk_XWGtfaXbk4WBWGTp_PGWup2oM0Q',
    appId: '1:360358999157:android:54907695aa0201710c743c',
    messagingSenderId: '360358999157',
    projectId: 'chat-app-38a80',
    storageBucket: 'chat-app-38a80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-ztEA3JDEGMKFHEpwrKXRW30kMqj9d4',
    appId: '1:360358999157:ios:ee559340b4475a1f0c743c',
    messagingSenderId: '360358999157',
    projectId: 'chat-app-38a80',
    storageBucket: 'chat-app-38a80.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
